import './globals.css'
import localFont from 'next/font/local'
import PerformanceMonitor from '@/components/PerformanceMonitor'
import Providers from '@/components/Providers'
import Script from "next/script"
import React from 'react'
import GoogleAdSense from '@/components/AdSense'
import GoogleAnalytics from '@/components/GoogleAnalytics'
import MicrosoftClarity from '@/components/MicrosoftClarity'
import AhrefsAnalytics from '@/components/AhrefsAnalytics'

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/satoshi-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/satoshi-medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/satoshi-bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-satoshi',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning className={satoshi.variable}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="manifest" href="/manifest.json" />
        
        {/* 字体预加载 */}
        <link rel="preload" href="/fonts/satoshi-regular.woff2" as="font" type="font/woff2" crossOrigin="" />
        <link rel="preload" href="/fonts/satoshi-medium.woff2" as="font" type="font/woff2" crossOrigin="" />
        
        {/* 外部服务预连接 */}
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="preconnect" href="https://accounts.google.com" />
        
        {/* Analytics Components */}
        <GoogleAnalytics />
        <MicrosoftClarity />
        <AhrefsAnalytics />
      </head>
      <body className={`${satoshi.variable} antialiased`}>
        <Providers>
          <PerformanceMonitor />
          <div id="root" style={{ minHeight: '100vh' }}>
            {children}
          </div>
        </Providers>

        {/* Google Identity Services */}
        <Script 
          src="https://accounts.google.com/gsi/client" 
          strategy="afterInteractive"
        />
        
        {/* Google AdSense Auto Ads */}
        <GoogleAdSense />
      </body>
    </html>
  )
}
